use_frameworks!

target 'MetalReFresh_Example' do
    platform :ios, '10.0'
    pod 'MetalReFresh', :path => '../'
    
    target 'MetalReFresh_Tests' do
        inherit! :search_paths
        
        
    end
end
